name: dva
channels:
  - defaults
dependencies:
  - annotated-types=0.6.0=py310hca03da5_0
  - attrs=24.3.0=py310hca03da5_0
  - blas=1.0=openblas
  - blinker=1.9.0=py310hca03da5_0
  - bottleneck=1.4.2=py310hbda83bc_0
  - brotli-python=1.0.9=py310h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - certifi=2025.1.31=py310hca03da5_0
  - cffi=1.17.1=py310h3eb5a62_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py310hca03da5_0
  - contourpy=1.3.1=py310h48ca7d4_0
  - cryptography=43.0.3=py310h8026fc7_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - dacite=1.8.1=py310hca03da5_0
  - flask=3.1.0=py310hca03da5_0
  - fonttools=4.55.3=py310h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - htmlmin=0.1.12=pyhd3eb1b0_1
  - idna=3.7=py310hca03da5_0
  - imagehash=4.3.1=py310hca03da5_0
  - itsdangerous=2.2.0=py310hca03da5_0
  - jinja2=3.1.5=py310hca03da5_0
  - joblib=1.4.2=py310hca03da5_0
  - jpeg=9e=h80987f9_3
  - kiwisolver=1.4.8=py310h313beb8_0
  - lcms2=2.16=he93ba84_0
  - lerc=4.0.0=h313beb8_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libllvm14=14.0.6=h19fdd8a_4
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libtiff=4.5.1=hc9ead59_1
  - libwebp-base=1.3.2=h80987f9_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - llvmlite=0.41.0=py310h514c7bf_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py310h80987f9_1
  - matplotlib-base=3.6.2=py310h8bbb115_0
  - multimethod=1.9.1=py310hca03da5_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.3=py310hca03da5_0
  - numba=0.58.1=py310h313beb8_0
  - numexpr=2.10.1=py310h5d9532f_0
  - numpy=1.23.5=py310hb93e574_0
  - numpy-base=1.23.5=py310haf87e8b_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.0.15=h80987f9_0
  - packaging=24.2=py310hca03da5_0
  - pandas=1.5.3=py310h46d7db6_0
  - patsy=1.0.1=py310hca03da5_0
  - phik=0.12.3=py310h48ca7d4_0
  - pillow=11.1.0=py310h84e58ab_0
  - pip=24.2=py310hca03da5_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py310hca03da5_0
  - pydantic-core=2.27.1=py310h2aea54e_0
  - pyopenssl=24.2.1=py310hca03da5_0
  - pyparsing=3.2.0=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_0
  - python=3.10.16=hb885b13_1
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - pytz=2024.1=py310hca03da5_0
  - pywavelets=1.8.0=py310h80987f9_0
  - pyyaml=6.0.2=py310h80987f9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.28.1=py310hca03da5_1
  - scipy=1.9.3=py310h20cbe94_2
  - seaborn=0.12.2=py310hca03da5_0
  - setuptools=75.1.0=py310hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h80987f9_0
  - statsmodels=0.13.5=py310hbda83bc_1
  - tangled-up-in-unicode=0.2.0=py310hca03da5_0
  - tbb=2021.8.0=h48ca7d4_0
  - tk=8.6.14=h6ba3021_0
  - tqdm=4.64.1=py310hca03da5_0
  - typeguard=4.2.1=py310hca03da5_0
  - typing-extensions=4.12.2=py310hca03da5_0
  - typing_extensions=4.12.2=py310hca03da5_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py310h80987f9_1
  - urllib3=1.26.19=py310hca03da5_0
  - visions=0.7.5=py310hca03da5_0
  - werkzeug=3.1.3=py310hca03da5_0
  - wheel=0.44.0=py310hca03da5_0
  - wordcloud=1.9.4=py310h80987f9_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - ydata-profiling=4.8.3=py310hca03da5_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
  
